# Generated by Django 6.1 on 2026-08-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Student",
        ),
    ]
