# Generated by Django 6.1 on 2026-08-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_user_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="user_name",
            new_name="username",
        ),
    ]
