# Generated by Django 6.1 on 2026-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_user_name_student_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
