# Generated by Django 6.1 on 2026-08-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.course",
            ),
        ),
    ]
